### ISSUE TITLE
[meta] Grands sujets "tech"

### ISSUE THREAD

**Issue by laem** [datagir/nosgestesclimat-site#1088]
> :construction: écriture de cette issue en cours

Dans cette issue, un premier jet de liste de sujets "tech" importants. Il s'agit de sujets qui ne sont pas purement tech. 

> Par exemple, si l'équipe estime qu'on a une dette trop importante sur un jeu de code, on le priorise "obligatoirement" ou on le traite en résiduel dans un sprint. Idem pour les bugs critiques qui n'ont pas à être priorisés (on arrête ce qu'on fait même un réunion et on le corrige) ou des bugs non prioritaires qu'on peut prioriser à chaque sprint sans trop impacter la feuille de route. 

À l'inverse, un sujet comme #801 n'est pas une obligation : on peut choisir de ne pas migrer vers Next, et la migration a un coût non négligeable, qui se chiffre en sprint(s). 

## Plutôt côté site
- [ ] #801 
## Plutôt côté modèle
- [ ] datagir/nosgestesclimat/issues/1907
- [ ]

**Comment by laem** [comment]
## À faire
- [ ] faire une liste à peu près complète des sujets
- [ ] sélectionner une partie d'entre-eux pour l'échéance intermédiaire mi-août 
- [ ] en parler aux côtés des autres sujets de la roadmap

**Comment by Clemog** [comment]
## Proposition prio Clément

### Court terme (fin août)

1. Versionnage du modèle et scripts de migration (à mon avis, un sprint pour 2 personnes)
1.0.1 Permettre l'accès à une partie du modèle seulement (pour moi c'est en même temps que le point 1)
2. Définition et mise en place d'une arborescence de fichiers structurées
3. Amélioration de la documentation

### Plus long terme

1. Déclinaison pour d'autres métriques
2. Listes dans publicodes
3. Biblio (+ storybook ?) de composants UI

### Semble très rapide (moins d'une demi journée pour chaque point) :

- enlever les dépendances externes faisant fuiter des IP
- Ouvrir le code du serveur

**Comment by laem** [comment]
## Proposition prio Maël

### Court terme (fin août)

1. Tests de charge mode groupe
2. Mode hors ligne
3. Réordonner les fichiers (rapide)

### Plus long terme

1. LLM
2. Versionnage et migration du modèle
4. Fusion ecolab-data et transport

**Comment by dxb** [comment]
**Court terme :**
1. TS 100%
2. versionnement du modèle et disponibilité via paquet ou api ?
3. simplifier architecture des dossiers/fichiers

**Long terme :**
1. refactoring général, passage à nextjs
2. avoir une librairie de composant ré-utilisable
3. Tailwind :)

**Comment by bjlaa** [comment]
Court terme : 

1 Tests de charge mode groupe
2 Réordonner les fichiers

Long terme :

1 passage à nextjs, TS
2 Design system / avoir une librairie de composant ré-utilisable
3 Tailwind <3
