### ISSUE TITLE
Docs: add a website's wiki

### ISSUE THREAD

**Issue by EmileRolley** [datagir/nosgestesclimat-site#701]
As the current work is to extend the area of people contributing to the project (e.g. #637, #535, #71, etc...), it's important to have a minimal documentation.

This is done via the GitHub's wiki: [nosgestesclimat-site's wiki](https://github.com/datagir/nosgestesclimat-site/wiki).

## Tasks

* [x] Setup a CI to update the wiki with the content of the [./docs](https://github.com/datagir/nosgestesclimat-site/tree/master/docs) folder.
* [x] Add pages:
   * [x] Translation
      * [x] Redirection page from the website's alert banner
      * [x] Add information about units translation.
      * [x] Complete non-tech user guide for translation   
      * [x] Custom publicodes mechanisms
   * [x] `PERSONNALISATION.md` cloned into `wiki/Customisation`
   * [x] Guide to update the documentation
