### ISSUE TITLE
Experimentation on model compression

### ISSUE THREAD

**Issue by EmileRolley** [datagir/nosgestesclimat-site#746]
In the context of the [Publicodes modularisation](https://pad.incubateur.net/s/7hVcQ-u5e), a first step could be to compact all every independent variables into only one constant when possible. This could lead to a consistent _complexity_ reduction -- _to determine_.

The idea it's that each node free of any dependency with a rule containing a question is compressed into a unique constant leaf.

The server will serve both the _compressed_ model and the set of _uncompressed_ rules, as it will be required to render the corresponding documentation page.

## Note

The tool should not only compress the model but just compiles YAML files into a single JSON file. We'll need to specify the target rule and will allow to generate the `co2-model-numerique.json` file as needed by https://github.com/datagir/nosgestesclimat/pull/1503.

## Investigation

After a first naive script implementation, here the result:

```yaml
# Before compression
nbNodes: 990,
totalDeg: 1288,
averageDeg: 1.301010101010101,
maxDegOut: 19,
maxDegIn: 15

# After compression
nbNodes: 379,
totalDeg: 560,
averageDeg: 1.4775725593667546,
maxDegOut: 13,
maxDegIn: 15
```

**This means a potential reduction of ~60% of the number of rules.**

#### Base french model -- commit ref: [d9e209447c9a61ba4aee0aac31ff1d037b23f1f2](https://github.com/datagir/nosgestesclimat/commit/d9e209447c9a61ba4aee0aac31ff1d037b23f1f2)

Number of rules: 1200

##### Time elapsed to instantiate the engine

**In localhost**:

|       Mode      | Time elapsed (ms) |
|:---------------:|:------------------|
|  No throttling  | ~780              |
| Mid-tier mobile | ~3000             |
|  Low-end mobile | ~4400             |

#### Opti 1 -- commit ref: [99b3665241da04ae28b7da9a589700abbda00555](https://github.com/datagir/nosgestesclimat/pull/1650/commits/99b3665241da04ae28b7da9a589700abbda00555)

Number of rules: 746 (compression of 37.8%)

> Rules containing an `applicable si` or `non applicable si` mechanism aren't folded yet.

##### Time elapsed to instantiate the engine

**In localhost**:

|       Mode      | Time elapsed (ms) | Time saved (%) |
|:---------------:|:------------------|:--------------:|
|  No throttling  | ~500              | 35.8           |
| Mid-tier mobile | ~2000             | 33.3           |
|  Low-end mobile | ~3000             | 31.8           |

## Tasks

- [x] Analyse the gain in term of removed rules.
- [x] Lets migrate to use the Publicodes utility functions.
- [x] There is some issues with the personas. List of those who aren't working properly:
  - [x] `2 tons`
  - [x] `Corentin from Paris`
  - [x] `Nolan de Neuilly`
  > Note: it seems related to the `recalcul` mechanism.
- [ ] If conclusive, improve the `rulesToJSON` script to compress rules before compiling to JSON.
- [ ] Support the rules translations with the compressed model.
- [ ] Support the compressed model in the documentation rendering.

**Comment by EmileRolley** [comment]
The first result of the experimentation show that the compression could be bring a significant perfs improvement -- ~35% of time saved to instantiate the Publicodes engine and almost 40% of rules deletion. Therefore, the next step is to ship a first alpha version of the tool to be used in production by NGC.

Related issues could be found in the related repository: TODO
