### ISSUE TITLE
[meta] Several tasks to improve the translation workflow

### ISSUE THREAD

**Issue by EmileRolley** [datagir/nosgestesclimat-site#782]
> Our current translation framework is a bit of a hinder to the general evolution of nosgestesclimat, even in French, since we want to maintain an updated english version
> This PR aims to make the day to day content evolutions more fluid

* [x] datagir/nosgestesclimat-site#871 -- done in https://github.com/datagir/nosgestesclimat/pull/1757
* [ ] Print more detailed diffs in the `check:ui`.
* [ ] Add commit prehooks to automatically updates `.lock` and translate if it's only a typo correction.
* [x] Add an interactive mode to translate rule by rule: asking for automatic translation -- done in https://github.com/datagir/nosgestesclimat/pull/1757.
* [ ] Setup prettier to format YAML files and add it to the CI workflow -> fixing trailing whitespaces? (https://makandracards.com/makandra/11541-how-to-not-leave-trailing-whitespace-using-your-editor-or-git)
* [ ] Add a threshold for automatic translation: typo corrections don't trigger automatic translation. 
* [x] Fix bug new rules translation broken (https://github.com/datagir/nosgestesclimat/commit/bcbbfb33b43055372c3cd229a1c85f5a6071f3ab)
* [x] Fix line breaking in yaml (https://github.com/datagir/nosgestesclimat/commit/b636ba3a79b009e8ebdbcc0ce5b12c4bb04639c1)

## Bug

* [x] datagir/nosgestesclimat#1765 -- done in https://github.com/datagir/nosgestesclimat/pull/1757

**Comment by Clemog** [comment]
The row formatting issue that we thought was fixed appears not to be...



![Image](https://user-images.githubusercontent.com/55186402/221183446-a888b1f3-fcd6-4b64-919d-3391413c4022.png)
