### ISSUE TITLE
[META] Nouvelles régions I18N

### ISSUE THREAD

**Issue by Clemog** [datagir/nosgestesclimat-site#906]
Cette méta concerne majoritairement des sujets "site" mais également quelques points méthodo (ou du moins la manière d'exposer et de parler de la méthodo ;) )

### A faire rapidement

- [ ] #897
- [ ] Clarifier la position du message de localisation ? Dans le test ? Dans la documentation ? Comment : drapeau, forme du pays ? Justifier nos choix qque part

### Idées pour plus tard

- [ ] Investiguer également d'autres déclinaisaisons de paramètres "généralisables" (services sociétaux via PIB ? d'autres FE dépendant du mix mais non paramétré, via une règle de 3 ? Notamment la voiture électrique, le train..)
- [ ] Ajouter une page langage pour mettre en valeur la traduction anglaise
- [ ] Ajouter une page par pays avec les diff
- [ ] Ajouter un comparateur de pays
